#!/bin/bash

MAX_COUNT=72
WORD_COUNT="$(head -n1 < $1 | wc -c)"
RED='\033[0;31m'

if [ $WORD_COUNT -gt $MAX_COUNT ]; then
    echo ""
    echo -e "${RED}ERROR: Your commit message is too long ($WORD_COUNT > $MAX_COUNT chars)!"
    exit 1
fi

